services:
  db: 
    image: postgres:14
    container_name: server-postgresql
    environment:
      POSTGRES_USER: tp_pr2
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: tp_pr2
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  java-app:
    image: openjdk:17
    container_name: java-app
    depends_on:
      - db
    ports:
      - "2000:2000"
    volumes:
      - ./app.jar:/app/app.jar
    environment:
      DB_HOST: db
      DB_PORT: 5432
    entrypoint: ["sh", "-c", "java -jar /app/app.jar --DB_NAME=tp_pr2 --DB_USER=tp_pr2 --DB_PASSWORD=123 --DB_SERVER=db --DB_SERVER_PORT=5432"]
    
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - java-app
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro

